export const LOGIN_REQUEST= "LOGIN_REQUEST"
export const LOGIN_SUCCESS= "LOGIN_SUCCESS"
export const LOGIN_FAIL= "LOGIN_FAIL";



export const SIGNUP_REQUEST= "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS= "SIGNUP_SUCCESS"
export const SIGNUP_FAIL= "SIGNUP_FAIL";
export const CLEAR_ERRORS="CLEAR_ERRORS"


export const LOAD_USER_REQUEST= "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS= "LOAD__USER_SUCCESS"
export const LOAD_USER_FAIL= "LOAD_USER_FAIL";

export const LOGOUT_REQUEST= "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS"
export const LOGOUT_FAIL= "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST= "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS= "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_RESET= "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL= "UPDATE_PROFILE_FAIL";


export const UPDATE_PASSWORD_REQUEST= "UPDATE_PROFILE_REQUEST"
export const UPDATE_PASSWORD_SUCCESS= "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PASSWORD_RESET= "UPDATE_PROFILE_RESET";
export const UPDATE_PASSWORD_FAIL= "UPDATE_PROFILE_FAIL";

export const FORGOT_PASSWORD_REQUEST= "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS= "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_RESET= "FORGOT_PASSWORD_RESET";
export const FORGOT_PASSWORD_FAIL= "FORGOT_PASSWORD_FAIL";


export const RESET_PASSWORD_REQUEST= "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS= "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_RESET= "RESET_PASSWORD_RESET";
export const RESET_PASSWORD_FAIL= "RESET_PASSWORD_FAIL";